version: '3.3'
services:
  decadevs_docker_victor:
    container_name: decadevs-docker-victor
    image: decadevs-docker-victor
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: victor
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: 123456